from typing import Protocol

class DocumentRepository(Protocol):
    async def add(self, document) -> None:
        ...
    async def get(self, document_id: str):
        ...
    async def update(self, document, document_id: str) -> None:
        ...
        
    async def add_version(self, document_version) -> None:
        ...

    async def get_version(self, document_version_id: str):
        ...

    async def get_versions_by_document(self, document_pk: int):
        ...
